# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=500)),
                ('photo_link', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=500)),
                ('episode_link', models.CharField(max_length=1000)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HindiCartoon.Cartoons')),
            ],
        ),
    ]
