# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HindiCartoon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartoons',
            new_name='Cartoon',
        ),
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Episode',
        ),
    ]
