# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HindiCartoon', '0004_auto_20170512_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='episode',
            new_name='season',
        ),
    ]
