# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HindiCartoon', '0005_auto_20170512_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='cartoon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HindiCartoon.Cartoon'),
            preserve_default=False,
        ),
    ]
