# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HindiCartoon', '0006_episode_cartoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCartoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
